"""Regenerate dist/ and docs/model/ from every LinkML module under schema/.

Rules in SPEC-toolchain.md: one draft 2020-12 JSON Schema per module (built in-process
without "null" types and without key sorting), docs per module, a generated dist/README.md,
stale outputs removed, empty schema/ is a no-op, fail fast.
Also writes dist/viewer/ by default (skip with --no-viewer-schemas), a cross-file $ref
variant for a schema viewer, gitignored and never drift-tested.
"""
from pathlib import Path
import argparse, json, shutil, subprocess, sys

import yaml
from linkml.generators.jsonschemagen import JsonSchemaGenerator

ROOT = Path(__file__).resolve().parents[1]
SCHEMA, DIST, DOCS, VIEWER = ROOT / "schema", ROOT / "dist", ROOT / "docs" / "model", ROOT / "dist" / "viewer"
DRAFT = "https://json-schema.org/draft/2020-12/schema"
VIEWER_README = """# Cross-referenced schemas for a schema viewer

Generated by default by `uv run python scripts/build.py` (skip with `--no-viewer-schemas`).
Do not edit; not committed.

Unlike `dist/*.schema.json`, which is self-contained, each file here keeps only the
classes and enums its own `schema/<module>.yaml` declares, and references every other
module's classes by a plain relative filename, e.g. `"common.schema.json#/$defs/Quantity"`.
Upload the files you need together to a viewer that resolves cross-file `$ref`s, such as
rcpc-schema-viewer.
"""


def run(*args: str) -> str:
    return subprocess.run(args, check=True, capture_output=True, text=True, encoding="utf-8").stdout


def write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def build(module: Path) -> tuple[str, dict]:
    """Emit the module's JSON Schema and docs; return its description and schema dict."""
    schema = dict(JsonSchemaGenerator(str(module), include_null=False).generate())
    schema["$schema"] = DRAFT
    write(DIST / f"{module.stem}.schema.json", json.dumps(schema, indent=2) + "\n")
    shutil.rmtree(DOCS / module.stem, ignore_errors=True)
    run("gen-doc", "--no-mergeimports", "-d", str(DOCS / module.stem), str(module))
    description = str(yaml.safe_load(module.read_text(encoding="utf-8")).get("description", "")).strip()
    return description, schema


def remove_stale(keep: set[str]) -> None:
    for stale in DIST.glob("*.schema.json"):
        if stale.name.removesuffix(".schema.json") not in keep:
            stale.unlink()
    for stale in (d for d in DOCS.iterdir() if d.is_dir() and d.name not in keep):
        shutil.rmtree(stale)


def owners(modules: list[Path]) -> dict[str, str]:
    """Map every class/enum name to the module stem whose own YAML declares it."""
    result: dict[str, str] = {}
    for module in modules:
        doc = yaml.safe_load(module.read_text(encoding="utf-8"))
        for name in {**doc.get("classes", {}), **doc.get("enums", {})}:
            result[name] = module.stem
    return result


def link(schema: dict, stem: str, owner: dict[str, str]) -> dict:
    """Cross-file $ref variant: keep only this module's own $defs, ref the rest by filename."""
    linked = json.loads(json.dumps(schema))

    def rewrite(node: object) -> None:
        if isinstance(node, dict):
            ref = node.get("$ref", "")
            if isinstance(ref, str) and ref.startswith("#/$defs/"):
                name = ref.removeprefix("#/$defs/")
                if owner.get(name, stem) != stem:
                    node["$ref"] = f"{owner[name]}.schema.json#/$defs/{name}"
            for value in node.values():
                rewrite(value)
        elif isinstance(node, list):
            for item in node:
                rewrite(item)

    rewrite(linked)
    linked["$defs"] = {name: d for name, d in linked["$defs"].items() if owner.get(name, stem) == stem}
    return linked


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-viewer-schemas", dest="viewer_schemas", action="store_false")
    args = parser.parse_args()

    modules = sorted(SCHEMA.glob("*.yaml"))
    DIST.mkdir(exist_ok=True)
    DOCS.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated schemas", "", "Generated from `schema/` by `uv run python scripts/build.py`. Do not edit.", ""]
    schemas: dict[str, dict] = {}
    for m in modules:
        description, schema = build(m)
        schemas[m.stem] = schema
        lines.append(f"- `{m.stem}.schema.json` (JSON Schema draft 2020-12): {description}")
    lines += ["No modules exist under `schema/` yet."] if not modules else []
    remove_stale({m.stem for m in modules})
    write(DIST / "README.md", "\n".join(lines) + "\n")

    if args.viewer_schemas and modules:
        shutil.rmtree(VIEWER, ignore_errors=True)
        VIEWER.mkdir(parents=True, exist_ok=True)
        owner = owners(modules)
        for m in modules:
            write(VIEWER / f"{m.stem}.schema.json", json.dumps(link(schemas[m.stem], m.stem, owner), indent=2) + "\n")
        write(VIEWER / "README.md", VIEWER_README)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except subprocess.CalledProcessError as failure:
        sys.stderr.write(failure.stderr or failure.stdout)
        sys.exit(failure.returncode or 1)
